### ISSUE TITLE
Position is not a correct google maps coordinate [Bug]

### ISSUE THREAD

**Issue by crashza** [grtswt/check_mk#1]
HI Firstly thanks for the awesome plugin. I noticed a bug when trying to place hosts in SA on the Map, It seems its the following line at fault 

if not re.match("^\d{1,3}(.\d{1,15})?,?\d{1,3}(.\d{1,15})?$", value):

in wato_position_attribute_picker.py

It does not allow for the first number to be negative.

Regards
Trevor Steyn

**Comment by grtswt** [comment]
How very true. New version coming up.

**Comment by urplo** [comment]
Hi, are there are any news to that? Because the problem unfortunately still occurs.
Kind regards,
Ursula
